using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json;
using VideoDownloader.Data;

namespace VideoDownloader.Controllers;

[ApiController]
[Route("api/media")]
[Authorize]
public class MediaController : ControllerBase
{
    private readonly AppDbContext _db;

    // ─── yt-dlp anti-detection args ──────────────────────────────────────────
    // بيخلي yt-dlp يبان زي Chrome browser عادي بدل bot
    private const string AntiBlockArgs =
        "--user-agent \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) " +
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36\" " +
        "--add-header \"Accept-Language:en-US,en;q=0.9\" " +
        "--add-header \"Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\" " +
        "--add-header \"Sec-Fetch-Mode:navigate\" " +
        "--no-check-certificates " +
        "--extractor-retries 5 " +
        "--sleep-interval 1 --max-sleep-interval 3 ";

    public MediaController(AppDbContext db)
    {
        _db = db;
    }

    // ─── Analyze ─────────────────────────────────────────────────────────────
    [HttpPost("analyze")]
    public async Task<IActionResult> Analyze([FromBody] MediaRequestDto dto)
    {
        try
        {
            await TrackRequest();
            var platform = DetectPlatform(dto.Url);

            if (platform == "spotify")
                return await AnalyzeSpotify(dto.Url);

            var isPlaylist = IsPlaylist(dto.Url);

            if (isPlaylist)
            {
                var result  = await RunYtDlp($"--flat-playlist -J \"{dto.Url}\"");
                var json    = JsonDocument.Parse(result).RootElement;
                var entries = json.GetProperty("entries").EnumerateArray().ToList();

                return Ok(new
                {
                    type      = "playlist",
                    platform,
                    title     = json.GetProperty("title").GetString(),
                    itemCount = entries.Count,
                    items     = entries.Select((e, i) => new
                    {
                        index     = i,
                        id        = e.TryGetProperty("id",        out var id) ? id.GetString()  : null,
                        title     = e.TryGetProperty("title",     out var t)  ? t.GetString()   : null,
                        duration  = e.TryGetProperty("duration",  out var d)
                                    && d.ValueKind == JsonValueKind.Number    ? d.GetDouble()   : 0,
                        thumbnail = e.TryGetProperty("thumbnail", out var tn) ? tn.GetString()  : null,
                        url       = BuildVideoUrl(platform,
                                    e.TryGetProperty("id", out var vid) ? vid.GetString() : "")
                    }),
                    availableQualities = GetQualities(platform)
                });
            }
            else
            {
                var result = await RunYtDlp($"-J --no-playlist \"{dto.Url}\"");
                var json   = JsonDocument.Parse(result).RootElement;

                var formats = json.GetProperty("formats")
                    .EnumerateArray()
                    .Where(f => f.TryGetProperty("height", out var h)
                                && h.ValueKind == JsonValueKind.Number)
                    .Select(f => f.GetProperty("height").GetInt32())
                    .Distinct()
                    .OrderByDescending(h => h)
                    .ToList();

                var hasSubs     = json.TryGetProperty("subtitles",          out var subs)
                                  && subs.ValueKind     == JsonValueKind.Object
                                  && subs.EnumerateObject().Any();
                var hasAutoSubs = json.TryGetProperty("automatic_captions", out var autoCaps)
                                  && autoCaps.ValueKind == JsonValueKind.Object
                                  && autoCaps.EnumerateObject().Any();

                return Ok(new
                {
                    type      = "video",
                    platform,
                    title     = json.GetProperty("title").GetString(),
                    duration  = json.GetProperty("duration").GetDouble(),
                    thumbnail = json.GetProperty("thumbnail").GetString(),
                    uploader  = json.TryGetProperty("uploader", out var up) ? up.GetString() : null,
                    subtitles = new
                    {
                        available        = hasSubs || hasAutoSubs,
                        hasManual        = hasSubs,
                        hasAutoGenerated = hasAutoSubs,
                        languages        = hasSubs
                            ? subs.EnumerateObject().Select(s => s.Name).Take(10)
                            : hasAutoSubs
                            ? autoCaps.EnumerateObject().Select(s => s.Name).Take(10)
                            : Enumerable.Empty<string>()
                    },
                    availableQualities = GetQualities(platform, formats)
                });
            }
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    // ─── Download ────────────────────────────────────────────────────────────
    [HttpPost("download")]
    public async Task<IActionResult> Download([FromBody] MediaDownloadDto dto)
    {
        try
        {
            await TrackRequest();
            var platform = DetectPlatform(dto.Url);

            if (platform == "spotify")
                return await DownloadSpotify(dto.Url);

            var format = dto.Quality switch
            {
                "2160" => "bestvideo[height<=2160]+bestaudio/best[height<=2160]",
                "1080" => "bestvideo[height<=1080]+bestaudio/best[height<=1080]",
                "720"  => "bestvideo[height<=720]+bestaudio/best[height<=720]",
                "480"  => "bestvideo[height<=480]+bestaudio/best[height<=480]",
                "360"  => "bestvideo[height<=360]+bestaudio/best[height<=360]",
                "mp3"  => "bestaudio[ext=mp3]/bestaudio",
                "m4a"  => "bestaudio[ext=m4a]/bestaudio",
                _      => "best"
            };

            var result = await RunYtDlp($"-g -f \"{format}\" \"{dto.Url}\"");
            var links  = result.Trim().Split('\n');

            return Ok(new
            {
                platform,
                quality  = dto.Quality,
                videoUrl = links.Length > 0 ? links[0].Trim() : null,
                audioUrl = links.Length > 1 ? links[1].Trim() : null,
                isAudio  = dto.Quality is "mp3" or "m4a"
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    // ─── Compress ────────────────────────────────────────────────────────────
    // بيحمل الفيديو على السيرفر → يضغطه بـ FFmpeg → يرجعه base64
    // استخدمه لما تريد توفير مساحة مع نفس الجودة تقريبًا (CRF 28 = ~40% أصغر)
    [HttpPost("compress")]
    public async Task<IActionResult> Compress([FromBody] CompressRequestDto dto)
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(tempDir);

        var inputPath  = Path.Combine(tempDir, "input.mp4");
        var outputPath = Path.Combine(tempDir, "output.mp4");

        try
        {
            await TrackRequest();
            var platform = DetectPlatform(dto.Url);

            // ── 1. Get CDN links ──────────────────────────────────
            var format = dto.Quality switch
            {
                "1080" => "bestvideo[height<=1080]+bestaudio/best[height<=1080]",
                "720"  => "bestvideo[height<=720]+bestaudio/best[height<=720]",
                "480"  => "bestvideo[height<=480]+bestaudio/best[height<=480]",
                "360"  => "bestvideo[height<=360]+bestaudio/best[height<=360]",
                _      => "bestvideo[height<=720]+bestaudio/best[height<=720]"
            };

            // ── 2. Download + mux directly via yt-dlp + FFmpeg ───
            // yt-dlp بيحمل ويعمل mux في نفس الوقت ← أسرع من طريقتين منفصلتين
            var dlArgs =
                $"-f \"{format}\" " +
                $"--merge-output-format mp4 " +
                $"-o \"{inputPath}\" " +
                $"--no-playlist " +
                $"\"{dto.Url}\"";

            await RunYtDlp(dlArgs);

            // ── 3. Compress with FFmpeg ───────────────────────────
            // CRF 28: جودة كويسة مع ضغط ~40% أقل مساحة
            // preset fast: سريع على السيرفر
            // scale: لو الفيديو أكبر من الـ quality المطلوبة، يصغره
            var targetHeight = dto.Quality switch
            {
                "1080" => 1080, "720" => 720, "480" => 480, "360" => 360, _ => 720
            };

            var ffmpegArgs =
                $"-i \"{inputPath}\" " +
                $"-vf \"scale='min(iw,{targetHeight*16/9})':-2\" " +
                $"-c:v libx264 -crf 28 -preset fast " +
                $"-c:a aac -b:a 128k " +
                $"-movflags +faststart " +   // ← مهم: بيخلي الفيديو يشتغل وهو بيتحمل
                $"-y \"{outputPath}\"";

            await RunProcess("ffmpeg", ffmpegArgs);

            // ── 4. Return result ──────────────────────────────────
            var originalSize   = new FileInfo(inputPath).Length;
            var compressedSize = new FileInfo(outputPath).Length;
            var savedPercent   = (int)((1.0 - (double)compressedSize / originalSize) * 100);

            var bytes    = await System.IO.File.ReadAllBytesAsync(outputPath);
            var base64   = Convert.ToBase64String(bytes);

            return Ok(new
            {
                platform,
                quality          = dto.Quality,
                originalSizeKb   = originalSize   / 1024,
                compressedSizeKb = compressedSize / 1024,
                savedPercent,
                base64,
                fileName = $"video_{dto.Quality}p_compressed.mp4"
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        finally
        {
            // تنظيف الملفات المؤقتة دايمًا
            if (Directory.Exists(tempDir))
                Directory.Delete(tempDir, true);
        }
    }

    // ─── Subtitles ───────────────────────────────────────────────────────────
    [HttpPost("subtitles")]
    public async Task<IActionResult> GetSubtitles([FromBody] SubtitleRequestDto dto)
    {
        try
        {
            await TrackRequest();

            var lang    = dto.Language ?? "en";
            var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);

            var args = $"--write-subs --sub-langs \"{lang}\" " +
                       $"--skip-download --no-playlist " +
                       $"-o \"{tempDir}/sub\" \"{dto.Url}\"";
            await RunYtDlp(args);

            var subFile = Directory.GetFiles(tempDir).FirstOrDefault();
            if (subFile == null)
            {
                args = $"--write-auto-subs --sub-langs \"{lang}\" " +
                       $"--skip-download --no-playlist " +
                       $"-o \"{tempDir}/sub\" \"{dto.Url}\"";
                await RunYtDlp(args);
                subFile = Directory.GetFiles(tempDir).FirstOrDefault();
            }

            if (subFile == null)
                return NotFound(new { message = $"No subtitles found for language: {lang}" });

            var content = await System.IO.File.ReadAllTextAsync(subFile);
            var ext     = Path.GetExtension(subFile).TrimStart('.');
            Directory.Delete(tempDir, true);

            return Ok(new
            {
                language  = lang,
                format    = ext,
                content,
                plainText = ExtractPlainText(content, ext)
            });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    // ─── Playlist selective ──────────────────────────────────────────────────
    [HttpPost("playlist/download")]
    public async Task<IActionResult> PlaylistDownload([FromBody] PlaylistDownloadDto dto)
    {
        try
        {
            await TrackRequest();

            var format = dto.Quality switch
            {
                "1080" => "bestvideo[height<=1080]+bestaudio/best[height<=1080]",
                "720"  => "bestvideo[height<=720]+bestaudio/best[height<=720]",
                "480"  => "bestvideo[height<=480]+bestaudio/best[height<=480]",
                "mp3"  => "bestaudio[ext=mp3]/bestaudio",
                "m4a"  => "bestaudio[ext=m4a]/bestaudio",
                _      => "best"
            };

            var tasks = dto.Urls.Select(async url =>
            {
                try
                {
                    var result = await RunYtDlp($"-g -f \"{format}\" \"{url}\"");
                    var links  = result.Trim().Split('\n');
                    return new
                    {
                        url,
                        success  = true,
                        videoUrl = links.Length > 0 ? links[0].Trim() : null,
                        audioUrl = links.Length > 1 ? links[1].Trim() : null,
                        error    = (string?)null
                    };
                }
                catch (Exception ex)
                {
                    return new
                    {
                        url,
                        success  = false,
                        videoUrl = (string?)null,
                        audioUrl = (string?)null,
                        error    = (string?)ex.Message
                    };
                }
            });

            var results = await Task.WhenAll(tasks);
            return Ok(new { items = results });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    // ─── Spotify Helpers ─────────────────────────────────────────────────────
    private async Task<IActionResult> AnalyzeSpotify(string url)
    {
        await RunProcess("spotdl", $"--print-errors save \"{url}\"");
        return Ok(new
        {
            type     = "audio",
            platform = "spotify",
            message  = "Spotify track detected",
            url,
            availableQualities = new[]
            {
                new { label = "MP3 320kbps", value = "mp3", type = "audio" },
                new { label = "M4A",         value = "m4a", type = "audio" }
            }
        });
    }

    private async Task<IActionResult> DownloadSpotify(string url)
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(tempDir);

        await RunProcess("spotdl", $"download \"{url}\" --output \"{tempDir}\"");

        var file = Directory.GetFiles(tempDir).FirstOrDefault();
        if (file == null)
            return BadRequest(new { message = "Spotify download failed" });

        var bytes    = await System.IO.File.ReadAllBytesAsync(file);
        var base64   = Convert.ToBase64String(bytes);
        var fileName = Path.GetFileName(file);
        Directory.Delete(tempDir, true);

        return Ok(new { platform = "spotify", fileName, base64, message = "Download successful" });
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────
    private static string ExtractPlainText(string content, string format)
    {
        var lines = content.Split('\n');
        if (format == "vtt")
            return string.Join(" ", lines
                .Where(l => !l.StartsWith("WEBVTT") && !l.Contains("-->") &&
                            !string.IsNullOrWhiteSpace(l) && !l.Trim().All(char.IsDigit))
                .Select(l => l.Trim()).Distinct());
        if (format == "srt")
            return string.Join(" ", lines
                .Where(l => !l.Contains("-->") &&
                            !string.IsNullOrWhiteSpace(l) && !l.Trim().All(char.IsDigit))
                .Select(l => l.Trim()));
        return content;
    }

    private static string DetectPlatform(string url) => url switch
    {
        var u when u.Contains("youtube.com") || u.Contains("youtu.be") => "youtube",
        var u when u.Contains("facebook.com") || u.Contains("fb.watch") => "facebook",
        var u when u.Contains("tiktok.com")    => "tiktok",
        var u when u.Contains("instagram.com") => "instagram",
        var u when u.Contains("soundcloud.com") => "soundcloud",
        var u when u.Contains("spotify.com")   => "spotify",
        _ => "unknown"
    };

    private static string BuildVideoUrl(string platform, string? id) =>
        platform == "youtube" ? $"https://www.youtube.com/watch?v={id}" : id ?? "";

    private static bool IsPlaylist(string url) =>
        url.Contains("playlist?list=") || (url.Contains("list=") && !url.Contains("watch?v="));

    private static List<object> GetQualities(string platform, List<int>? heights = null)
    {
        if (platform is "soundcloud" or "spotify")
            return new List<object>
            {
                new { label = "MP3", value = "mp3", type = "audio", available = true },
                new { label = "M4A", value = "m4a", type = "audio", available = true }
            };

        var all = new List<(string label, string value, string type)>
        {
            ("4K - 2160p", "2160", "video"),
            ("1080p",      "1080", "video"),
            ("720p",       "720",  "video"),
            ("480p",       "480",  "video"),
            ("360p",       "360",  "video"),
            ("MP3 Audio",  "mp3",  "audio"),
            ("M4A Audio",  "m4a",  "audio"),
        };

        return all
            .Where(q => q.type == "audio" || heights == null ||
                        heights.Any(h => h >= int.Parse(q.value)))
            .Select(q => (object)new
            {
                label     = q.label,
                value     = q.value,
                type      = q.type,
                available = heights == null || q.type == "audio" ||
                            heights.Any(h => h >= int.Parse(q.value))
            })
            .ToList();
    }

    private async Task TrackRequest()
    {
        var claim = User.FindFirst("deviceId")?.Value;
        if (claim == null) return;
        var device = await _db.Devices.FindAsync(int.Parse(claim));
        if (device == null) return;
        device.RequestCount++;
        await _db.SaveChangesAsync();
    }

    // ─── Process Runners ─────────────────────────────────────────────────────
    // كل yt-dlp calls بتاخد AntiBlockArgs تلقائيًا
    private static Task<string> RunYtDlp(string args) =>
        RunProcess("yt-dlp", AntiBlockArgs + args);

    private static async Task<string> RunProcess(string exe, string args)
    {
        var psi = new ProcessStartInfo
        {
            FileName               = exe,
            Arguments              = args,
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            UseShellExecute        = false,
            CreateNoWindow         = true
        };

        using var process = Process.Start(psi)!;
        var output = await process.StandardOutput.ReadToEndAsync();
        var error  = await process.StandardError.ReadToEndAsync();
        await process.WaitForExitAsync();

        if (process.ExitCode != 0)
            throw new Exception(error);

        return output;
    }
}

// ─── DTOs ─────────────────────────────────────────────────────────────────────
public record MediaRequestDto(string Url);
public record MediaDownloadDto(string Url, string Quality);
public record CompressRequestDto(string Url, string Quality);
public record PlaylistDownloadDto(List<string> Urls, string Quality);
public record SubtitleRequestDto(string Url, string? Language);